/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LISTAWEB_H_RPCGEN
#define _LISTAWEB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct nombreArchivo {
	char *nombreAr;
};
typedef struct nombreArchivo nombreArchivo;

#define SERVIDORWEB 0x20000001
#define VER_SERVIDOR 1

#if defined(__STDC__) || defined(__cplusplus)
#define mostrarLista 1
extern  char ** mostrarlista_1(void *, CLIENT *);
extern  char ** mostrarlista_1_svc(void *, struct svc_req *);
#define mostrarCodigo 2
extern  char ** mostrarcodigo_1(nombreArchivo *, CLIENT *);
extern  char ** mostrarcodigo_1_svc(nombreArchivo *, struct svc_req *);
extern int servidorweb_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mostrarLista 1
extern  char ** mostrarlista_1();
extern  char ** mostrarlista_1_svc();
#define mostrarCodigo 2
extern  char ** mostrarcodigo_1();
extern  char ** mostrarcodigo_1_svc();
extern int servidorweb_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nombreArchivo (XDR *, nombreArchivo*);

#else /* K&R C */
extern bool_t xdr_nombreArchivo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LISTAWEB_H_RPCGEN */
