/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "listaWeb.h"

bool_t
xdr_nombreArchivo (XDR *xdrs, nombreArchivo *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombreAr, 2048))
		 return FALSE;
	return TRUE;
}
